global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:32222"]

  - job_name: "transaction-service"
    static_configs:
      - targets: ["transaction-service:32223"]
